services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cc-c-castino
    ports:
      - "3307:3306" # Access MySQL database on localhost:3307
    volumes:
      - mysql8.0-data:/var/lib/mysql
    networks:
      - cc-c-c-network

volumes:
  mysql8.0-data:

networks:
  cc-c-c-network:
